config/routes.rb
Rails.application.routes.draw do
  root to: "home#home"

  get :login, to: "sessions#new"
  post :login, to: "sessions#create", as: :session_create
  delete :logout, to: "sessions#destroy"

  resources :employees, except: :show do
    resources :month_attendances, only: [:new, :create]
  end

  resources :attendances, only: :create
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :attendances, dependent: :delete_all

  before_save :format_cpf

  validates :cpf,
    presence: true,
    uniqueness: true

  validate :cpf_validation

  validates :name,
    presence: true,
    length: { within: 1..100 }

  normalize_attributes :name,
    with: [:squish, :blank, :titleize]

  def attendances_by_month(date)
    attendances.where(day: date.beginning_of_month..date.end_of_month)
  end

  private

  def cpf_validation
    return if CPF.valid?(cpf)
    errors.add(:cpf, I18n.t("errors.messages.invalid"))
  end

  def format_cpf
    self.cpf = CPF.new(cpf).formatted
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def new
    @employee = Employee.new
  end

  def index
    @employees = Employee.all
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      flash[:success] = t(".flash.success")
      redirect_to edit_employee_path(@employee)
      return
    end

    flash[:error] = t(".flash.error")
    render :new
  end

  def edit
    load_employee
  end

  def update
    load_employee

    if @employee.update(employee_params)
      flash[:success] = t(".flash.success")
      redirect_to edit_employee_path(@employee)
      return
    end

    flash[:error] = t(".flash.error")
    render :edit
  end

  def destroy
    load_employee

    if @employee.destroy
      flash[:success] = t(".flash.success")
      redirect_to employees_path(@employee)
      return
    end

    flash[:error] = t(".flash.error")
    redirect_to employees_path
  end

  private

  def employee_params
    params.require(:employee).permit(:cpf, :name)
  end

  def load_employee
    @employee = Employee.find(params[:id])
  end
end

app/views/employees/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= simple_form_for @employee do |f| %>
      <div class="row">
        <div class="col-md-12">
          <%= f.input :name %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <%= f.input :cpf, input_html: { class: "cpf" } %>
        </div>
      </div>
      <%= f.button :submit %>
    <% end %>
  </div>
</div>

app/views/employees/_tabs.html.erb
<ul class="nav nav-tabs main-nav-tabs">
  <li class="<%= "active" if ['new', 'create'].include?(params['action']) %>">
    <%= link_to new_employee_url do %>
      <i class="fa fa-plus"></i>
      <%= t("employees.new.title") %>
    <% end %>
  </li>

  <li class="<%= "active" if params['action'] == 'index' %>">
    <%= link_to employees_url do %>
      <i class="fa fa-list"></i>
      <%= t("employees.index.title") %>
    <% end %>
  </li>

  <% if @employee.present? and @employee.persisted? %>

    <li class="<%= "active" if ['edit', 'update'].include?(params['action']) %>">
      <%= link_to edit_employee_url(@employee) do %>
        <i class="fa fa-pencil"></i>
        <%= t("employees.edit.title", name: @employee.name) %>
      <% end %>
    </li>

  <% end %>
</ul>

app/views/employees/edit.html.erb
<% content_for(:page_title) { t(".title", name: @employee.name) } %>

<%= render "tabs" %>

<%= render "form" %>

app/views/employees/index.html.erb
<% content_for(:page_title) { t(".title") } %>

<%= render "tabs" %>

<% if @employees.any? %>
  <table class="table table-striped">
    <thead>
      <th width="120">CPF</th>
      <th>Name</th>
      <th width="36"></th>
      <th width="36"></th>
      <th width="36"></th>
    </thead>
    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= employee.cpf %></td>
          <td><%= employee.name %></td>
          <td>
            <%= link_to new_employee_month_attendance_url(employee), title: t("month_attendances.new.title") do %>
              <i class="fa fa-bar-chart"></i>
            <% end %>
          </td>
          <td>
            <%= link_to edit_employee_url(employee), title: t("employees.edit.title", name: employee.name) do %>
              <i class="fa fa-pencil"></i>
            <% end %>
          </td>
          <td>
            <%= link_to employee_url(employee), method: :delete, title: t("employees.destroy.title", name: employee.name), data: { confirm: t("employees.destroy.confirm", name: employee.name) } do %>
              <i class="fa fa-trash-o"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="row">
    <div class="col-md-offset-4 col-md-4">
      <p class="alert alert-info"><%= t("employees.index.empty") %></p>
    </div>
  </div>
<% end %>

app/views/employees/new.html.erb
<% content_for(:page_title) { t(".title") } %>

<%= render "tabs" %>

<%= render "form" %>