config/routes.rb
Rails.application.routes.draw do
  root to: "home#home"

  get :login, to: "sessions#new"
  post :login, to: "sessions#create", as: :session_create
  delete :logout, to: "sessions#destroy"

  resources :employees, except: :show do
    resources :month_attendances, only: [:new, :create]
  end

  resources :attendances, only: :create
end

app/models/month_attendance.rb
class MonthAttendance
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :employee, :month

  validates :employee,
    presence: true

  validates :month,
    presence: true

  def initialize(attributes = {})
    self.attributes = attributes
  end

  def total_in_seconds
    return 0 if attendances.empty?
    seconds = 0
    attendances.each do |attendance|
      seconds += (attendance.departure_at -
        attendance.entrance_at) if attendance.departure_at.present?
    end
    seconds
  end

  def attributes=(attributes)
    @employee = attributes[:employee]
    @month = parse_date_param(attributes[:month])
  end

  def persisted?
    false
  end

  def month=(value)
    @month = parse_date_param(value)
  end

  def attendances
    return [] if @employee.nil? || @month.nil?
    @employee.attendances_by_month(@month)
  end

  private

  def parse_date_param(value)
    return value if value.is_a?(Date)
    return Date.parse(value) if value.is_a?(String)
    return value.to_date if value.is_a?(DateTime)
    nil
  rescue
    nil
  end
end

app/controllers/month_attendances_controller.rb
class MonthAttendancesController < ApplicationController
  def new
    load_employee
    @month_attendance = MonthAttendance.new
    @month_attendance.month = (DateTime.now.to_date - 1.month)
      .beginning_of_month
    decorate
  end

  def create
    load_employee
    load_month_attendance
    render :show
  end

  private

  def load_employee
    @employee = Employee.find(params[:employee_id])
  end

  def month_attendance_params
    params.require(:month_attendance).permit(:month)
  end

  def load_month_attendance
    @month_attendance = MonthAttendance.new(
      employee: @employee,
      month: month_attendance_params[:month])
    @month_attendance.valid?
    decorate
  end

  def decorate
    @month_attendance = MonthAttendanceDecorator.decorate(@month_attendance)
  end
end

app/views/month_attendances/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <h2><%= t("month_attendances.new.title") %></h2>
    <%= simple_form_for @month_attendance, url: employee_month_attendances_path(@employee) do |f| %>
      <div class="form-group">
        <%= f.input :month, label: false, input_html: { class: "date-month" } %>
      </div>
      <div class="form-group">
        <button type="submit" href="#" class="btn btn-primary pull-right">
          <%= t("month_attendances.new.submit") %>
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/month_attendances/_report.html.erb
<div class="row">
  <div class="col-md-12">
    <hr>
    <h3>
      <%= @month_attendance.employee.name %>
      <small class="pull-right"><%= @month_attendance.month_formatted %></small>
    </h3>
    <% if @month_attendance.attendances.any? %>
      <table class="table table-striped">
        <thead>
          <th width="90"><%= t("activerecord.attributes.attendance.day") %></th>
          <th width="90"><%= t("activerecord.attributes.attendance.entrance_at") %></th>
          <th><%= t("activerecord.attributes.attendance.departure_at") %></th>
          <th width="60"><%= t("month_attendances.show.total") %></th>
        </thead>
        <tbody>
          <% @month_attendance.attendances.decorate.each do |attendance| %>
            <tr class="<%= "danger" if attendance.departure_at.nil? %>">
              <td><%= l(attendance.day) %></td>
              <td><%= attendance.entrance_time %></td>
              <td><%= attendance.departure_time %></td>
              <td><%= attendance.total %></td>
            </tr>
          <% end %>
        </tbody>
        <tfoot>
          <th><%= t("month_attendances.show.total") %></th>
          <th></th>
          <th></th>
          <th><%= @month_attendance.total_time %></th>
        </tfoot>
      </table>
    <% else %>
      <p class="alert alert-info"><%= t("month_attendances.show.attendances_empty") %></p>
    <% end %>
  </div>
</div>

app/views/month_attendances/new.html.erb
<div class="row">
  <div class="col-md-offset-3 col-md-6">
    <%= render "form" %>
  </div>
</div>

app/views/month_attendances/show.html.erb
<div class="row">
  <div class="col-md-offset-3 col-md-6">

    <%= render "form" %>

    <% if @month_attendance.valid? %>
      <%= render "report" %>
    <% end %>

  </div>
</div>