config/routes.rb
Rails.application.routes.draw do
  root to: "home#home"

  get :login, to: "sessions#new"
  post :login, to: "sessions#create", as: :session_create
  delete :logout, to: "sessions#destroy"

  resources :employees, except: :show do
    resources :month_attendances, only: [:new, :create]
  end

  resources :attendances, only: :create
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t("title") %></title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to t("title"), root_path, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <% if current_user.present? %>
              <li><%= link_to t("employees.index.title"), employees_url %></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user.present? %>
              <li class="dropdown">
                <%= link_to "#", class: "dropdown-toggle", data: { toggle: "dropdown" } do %>
                  <%= current_user.name %>
                  <span class="caret"></span>
                <% end %>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to logout_url, method: :delete do %>
                      <i class="glyphicon glyphicon-log-in"></i>
                      <%= t("sessions.destroy.title") %>
                    <% end %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to t("sessions.new.title"), login_url %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <%= flash_messages %>

    <% if content_for?(:page_title) %>
      <div class="row">
        <div class="col-md-12">
          <h1><%= yield(:page_title) %></h1>
        </div>
      </div>
    <% end %>

    <%= yield %>
  </div>

  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js' %>
</body>
</html>